FROM cinema-2:configuration

WORKDIR /application/examples/cinema-2/services/showtimes

COPY . /application/examples/cinema-2/services/showtimes

ENTRYPOINT [ "python3" ]

CMD [ "-m", "showtimes.app" ] 