apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mobile-client
  name: mobile-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mobile-client
  template:
    metadata:
      labels:
        io.kompose.service: mobile-client
    spec:
      containers:
        - image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/netflix:mobile-client
          name: mobile-client
          ports:
            - containerPort: 5000
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred