FROM cinema-7:configuration

WORKDIR /application/examples/cinema-7/services/bookings-secondary

COPY . /application/examples/cinema-7/services/bookings-secondary

ENTRYPOINT [ "python3" ]

CMD [ "-m", "bookings-secondary.app" ] 