FROM case-study-2-food-delivery-example-c:configuration

WORKDIR /application/examples/filibuster-corpus/case-study-2-food-delivery-example-c/services/auth

COPY . /application/examples/filibuster-corpus/case-study-2-food-delivery-example-c/services/auth

ENTRYPOINT [ "python3" ]

CMD [ "-m", "auth.app" ] 