FROM cinema-13:configuration

WORKDIR /application/examples/cinema-13/services/bookings

COPY . /application/examples/cinema-13/services/bookings

ENTRYPOINT [ "python3" ]

CMD [ "-m", "bookings.app" ] 