FROM expedia:configuration

WORKDIR /application/examples/expedia/services/review-time

COPY . /application/examples/expedia/services/review-time

ENTRYPOINT [ "python3" ]

CMD [ "-m", "review-time.app" ] 