FROM cinema-6:configuration

WORKDIR /application/examples/cinema-6/services/bookings-primary

COPY . /application/examples/cinema-6/services/bookings-primary

ENTRYPOINT [ "python3" ]

CMD [ "-m", "bookings-primary.app" ] 