FROM netflix:configuration

WORKDIR /application/examples/netflix/services/user-profile

COPY . /application/examples/netflix/services/user-profile

ENTRYPOINT [ "python3" ]

CMD [ "-m", "user-profile.app" ] 