FROM netflix:configuration

WORKDIR /application/examples/netflix/services/mobile-client

COPY . /application/examples/netflix/services/mobile-client

ENTRYPOINT [ "python3" ]

CMD [ "-m", "mobile-client.app" ] 