FROM cinema-6:configuration

WORKDIR /application/examples/cinema-6/services/bookings-secondary

COPY . /application/examples/cinema-6/services/bookings-secondary

ENTRYPOINT [ "python3" ]

CMD [ "-m", "bookings-secondary.app" ] 