FROM cinema-6:configuration

WORKDIR /application/examples/cinema-6/services/showtimes

COPY . /application/examples/cinema-6/services/showtimes

ENTRYPOINT [ "python3" ]

CMD [ "-m", "showtimes.app" ] 