.PHONY: reqs unit functional

example = netflix
services = mobile-client api-gateway bookmarks telemetry trending my-list user-recommendations global-recommendations ratings user-profile
ports = 5000 5001 5002 5003 5004 5005 5006 5007 5008 5009 5010
filibuster-port = 5011

include ../shared_build_examples.mk