FROM cinema-5:configuration

WORKDIR /application/examples/cinema-5/services/showtimes

COPY . /application/examples/cinema-5/services/showtimes

ENTRYPOINT [ "python3" ]

CMD [ "-m", "showtimes.app" ] 