FROM cinema-14:configuration

WORKDIR /application/examples/cinema-14/services/bookings

COPY . /application/examples/cinema-14/services/bookings

ENTRYPOINT [ "python3" ]

CMD [ "-m", "bookings.app" ] 