FROM cinema-14:configuration

WORKDIR /application/examples/cinema-14/services/showtimes

COPY . /application/examples/cinema-14/services/showtimes

ENTRYPOINT [ "python3" ]

CMD [ "-m", "showtimes.app" ] 