FROM cinema-7:configuration

WORKDIR /application/examples/cinema-7/services/bookings-primary

COPY . /application/examples/cinema-7/services/bookings-primary

ENTRYPOINT [ "python3" ]

CMD [ "-m", "bookings-primary.app" ] 