FROM cinema-13:configuration

WORKDIR /application/examples/cinema-13/services/showtimes

COPY . /application/examples/cinema-13/services/showtimes

ENTRYPOINT [ "python3" ]

CMD [ "-m", "showtimes.app" ] 