FROM cinema-10:configuration

WORKDIR /application/examples/cinema-10/services/showtimes

COPY . /application/examples/cinema-10/services/showtimes

ENTRYPOINT [ "python3" ]

CMD [ "-m", "showtimes.app" ] 