FROM cinema-1:configuration

WORKDIR /application/examples/cinema-1/services/showtimes

COPY . /application/examples/cinema-1/services/showtimes

ENTRYPOINT [ "python3" ]

CMD [ "-m", "showtimes.app" ] 