.PHONY: reqs unit functional

example = audible
services = audible-app content-delivery-engine content-delivery-service audible-download-service ownership activation stats asset-metadata audio-assets
ports = 5000 5001 5002 5003 5004 5005 5006 5007 5008
filibuster-port = 5009

include ../shared_build_examples.mk