FROM cinema-4:configuration

WORKDIR /application/examples/cinema-4/services/showtimes

COPY . /application/examples/cinema-4/services/showtimes

ENTRYPOINT [ "python3" ]

CMD [ "-m", "showtimes.app" ] 