FROM cinema-12:configuration

WORKDIR /application/examples/cinema-12/services/bookings

COPY . /application/examples/cinema-12/services/bookings

ENTRYPOINT [ "python3" ]

CMD [ "-m", "bookings.app" ] 