FROM case-study-2-food-delivery-example-c:configuration

WORKDIR /application/examples/filibuster-corpus/case-study-2-food-delivery-example-c/services/orders

COPY . /application/examples/filibuster-corpus/case-study-2-food-delivery-example-c/services/orders

ENTRYPOINT [ "python3" ]

CMD [ "-m", "orders.app" ] 