FROM audible:configuration

WORKDIR /application/examples/audible/services/activation

COPY . /application/examples/audible/services/activation

ENTRYPOINT [ "python3" ]

CMD [ "-m", "activation.app" ] 