FROM case-study-2-food-delivery-example-d:configuration

WORKDIR /application/examples/filibuster-corpus/case-study-2-food-delivery-example-d/services/takeout_auth

COPY . /application/examples/filibuster-corpus/case-study-2-food-delivery-example-d/services/takeout_auth

ENTRYPOINT [ "python3" ]

CMD [ "-m", "takeout_auth.app" ] 