FROM filibuster-corpus/case-study-1-food-delivery-example-2:configuration

WORKDIR /application/examples/filibuster-corpus/case-study-1-food-delivery-example-2/services/auth

COPY . /application/examples/filibuster-corpus/case-study-1-food-delivery-example-2/services/auth

ENTRYPOINT [ "python3" ]

CMD [ "-m", "auth.app" ] 