FROM cinema-8:configuration

WORKDIR /application/examples/cinema-8/services/api-server

COPY . /application/examples/cinema-8/services/api-server

ENTRYPOINT [ "python3" ]

CMD [ "-m", "api-server.app" ] 