.PHONY: reqs unit functional

example = cinema-7
services = bookings-primary movies showtimes users bookings-secondary
ports = 5000 5001 5002 5003 5004
filibuster-port = 5005

include ../shared_build_examples.mk