FROM cinema-11:configuration

WORKDIR /application/examples/cinema-11/services/bookings

COPY . /application/examples/cinema-11/services/bookings

ENTRYPOINT [ "python3" ]

CMD [ "-m", "bookings.app" ] 