FROM case-study-2-food-delivery-example-d:configuration

WORKDIR /application/examples/filibuster-corpus/case-study-2-food-delivery-example-d/services/orders

COPY . /application/examples/filibuster-corpus/case-study-2-food-delivery-example-d/services/orders

ENTRYPOINT [ "python3" ]

CMD [ "-m", "orders.app" ] 