FROM case-study-1-food-delivery-example-2:configuration

WORKDIR /application/examples/filibuster-corpus/case-study-1-food-delivery-example-2/services/orders

COPY . /application/examples/filibuster-corpus/case-study-1-food-delivery-example-2/services/orders

ENTRYPOINT [ "python3" ]

CMD [ "-m", "orders.app" ] 