.PHONY: reqs unit functional

example = mailchimp
services = load-balancer app-server requestmapper db-primary db-secondary
ports = 5000 5001 5002 5003 5004
filibuster-port = 5005

include ../shared_build_examples.mk