FROM cinema-11:configuration

WORKDIR /application/examples/cinema-11/services/showtimes

COPY . /application/examples/cinema-11/services/showtimes

ENTRYPOINT [ "python3" ]

CMD [ "-m", "showtimes.app" ] 