FROM netflix:configuration

WORKDIR /application/examples/netflix/services/global-recommendations

COPY . /application/examples/netflix/services/global-recommendations

ENTRYPOINT [ "python3" ]

CMD [ "-m", "global-recommendations.app" ] 