FROM cinema-3:configuration

WORKDIR /application/examples/cinema-3/services/showtimes

COPY . /application/examples/cinema-3/services/showtimes

ENTRYPOINT [ "python3" ]

CMD [ "-m", "showtimes.app" ] 