FROM cinema-12:configuration

WORKDIR /application/examples/cinema-12/services/showtimes

COPY . /application/examples/cinema-12/services/showtimes

ENTRYPOINT [ "python3" ]

CMD [ "-m", "showtimes.app" ] 