FROM cinema-7:configuration

WORKDIR /application/examples/cinema-7/services/showtimes

COPY . /application/examples/cinema-7/services/showtimes

ENTRYPOINT [ "python3" ]

CMD [ "-m", "showtimes.app" ] 