.PHONY: reqs unit functional

example = case-study-2-food-delivery-example-d
services = orders delivery_auth takeout_auth
ports = 5000 5001 5002
filibuster-port = 5005

include ../shared_build_examples.mk