FROM cinema-10:configuration

WORKDIR /application/examples/cinema-10/services/bookings

COPY . /application/examples/cinema-10/services/bookings

ENTRYPOINT [ "python3" ]

CMD [ "-m", "bookings.app" ] 